name: Train Model - Dev then Prod

on:
  push:
    branches:
      - main

jobs:
  train-dev:
    name: Train on Dev Cluster
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Adding dataset path variable in job YAML
        run: envsubst < src/job-dev.yml > src/job-dev-processed.yml
        env:
          AML_DATA_PATH_DEV: ${{ vars.AML_DATA_PATH_DEV }}

      - name: Run AML job on Dev
        run: az ml job create --file src/job-dev-processed.yml --stream --web --resource-group ${{ vars.RSGROUP }} --workspace-name ${{ vars.WORKSPACE }}

  train-prod:
    name: Train on Prod Cluster
    needs: train-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Substitute variables in job YAML
        run: envsubst < src/job-prod.yml > src/job-prod-processed.yml
        env:
          AML_DATA_PATH_PROD: ${{ vars.AML_DATA_PATH_PROD }}

      - name: Run AML job on Prod
        run: az ml job create --file src/job-prod-processed.yml --stream --web --resource-group ${{ vars.RSGROUP_PROD }} --workspace-name ${{ vars.WORKSPACE_PROD }}
